name: Swag Labs WebdriverIO Automation Demo Framework

on:
    push:
        branch: ['main']

jobs:
    RunSwagLabsSuite:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                test-suite:
                    - swagLabs
            # feath repository code
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  feath-depth: 0
                  repository: ${{github.repository}}
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install node latest
              if: always()
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
            - name: Install node modules
              run: |
                  npm install
            - name: Update npm
              run: npm install -g npm@latest
            - name: Update dependencies
              run: |
                  rm -rf node_modules package-lock.json
                  npm install --legacy-peer-deps
            - name: Cache dependencies
              uses: actions/cache@v3
            - name: Run Swag Labs  suite
              if: always()
              run: |
                  npm run suite swagLabs
