name: Swag Labs WebdriverIO Automation Demo Framework
on: 
  workflow_call: 
    workflow_dispatch:
      inputs: 
        testEnvironment: 
          description: select environment which need to run in tests 
          required: false
          defualt: dev
          type: choose
          options:
            - Dev
            - Stage
            - PROD

jobs:
  RunSwagLabsSuite:
    runs-on: ubuntu-latest 
    strategy:
      matrix: 
        test-suites:
          - swagLabs

    steps:
      name: Checkout Source
      uses: checkout/checkout@v4
