name: Swag Labs WebdriverIO Automation Demo Framework
 
 on: 
  workflow_call: 
    workflow_dispatch:
      inputs: 
        testEnvironment: 
           description: select environment which need to run in tests 
            required: false
              defualt: dev
              type: choose
              options:
                - dev
                - stage
                - PROD

jobs:
  RunSwagLabsSuite:
    runs-on: ubuntu-latest 
    strategy:
      matrix: 
        test-suites:
          - swagLabs